# Generated by Django 3.2 on 2021-05-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=200, verbose_name='Yapılacak')),
                ('isActive', models.BooleanField(default=True, verbose_name='Yapıldı Mı?')),
            ],
            options={
                'verbose_name': 'Yapılacak',
                'verbose_name_plural': 'Yapılacaklar',
            },
        ),
    ]
