# Generated by Django 3.2 on 2021-05-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='Yapıldı Mı?'),
        ),
    ]
